-- Generated by PixelGen — sprite sheet quad + animation data
return {
  image = "player_walk.png",
  width = 128,
  height = 48,
  frames = {
    ["walk_000"] = { x = 0, y = 0, w = 32, h = 48, duration = 0.1250, ox = 16.0, oy = 48.0 },
    ["walk_001"] = { x = 32, y = 0, w = 32, h = 48, duration = 0.1250, ox = 16.0, oy = 48.0 },
    ["walk_002"] = { x = 64, y = 0, w = 32, h = 48, duration = 0.1250, ox = 16.0, oy = 48.0 },
    ["walk_003"] = { x = 96, y = 0, w = 32, h = 48, duration = 0.1250, ox = 16.0, oy = 48.0 },
  },
  animations = {
    ["walk"] = { fps = 8, loop = true, frames = { "walk_000", "walk_001", "walk_002", "walk_003" } },
  },
}
