-- Player: a controllable sprite with platformer-style physics.
--
-- Sprite sheet + animation data generated by pixegen
-- (https://github.com/DonAyers/pixegen) via its love2d export format:
--   node bin/pixegen.js sheet "..." --anim walk --view side \
--     --recipe nes-classic -s 32x48 --format love2d --name player \
--     -o ../smolbot/assets/sprites/player-walk/

local Player = {}
Player.__index = Player

local SPEED = 220
local GRAVITY = 1400
local JUMP_VELOCITY = -520

local SHEET_DIR = "assets/sprites/player-walk/"
local sheetData = require("assets.sprites.player-walk.player_walk")

local spriteImage = love.graphics.newImage(SHEET_DIR .. sheetData.image)
spriteImage:setFilter("nearest", "nearest")

-- Build a lookup of frame name -> { quad, pivot offset, duration }.
local frames = {}
for name, f in pairs(sheetData.frames) do
	frames[name] = {
		quad = love.graphics.newQuad(f.x, f.y, f.w, f.h, spriteImage:getDimensions()),
		ox = f.ox,
		oy = f.oy,
		duration = f.duration,
	}
end

local walkAnim = sheetData.animations.walk

function Player.new(x, y)
	local self = setmetatable({}, Player)
	self.x = x
	self.y = y
	self.width = 32
	self.height = 48
	self.vx = 0
	self.vy = 0
	self.onGround = false
	self.facing = 1 -- 1 = facing right, -1 = facing left
	self.animTimer = 0
	self.animFrame = 1
	return self
end

function Player:update(dt, groundY)
	self.vx = 0
	if love.keyboard.isDown("left", "a") then
		self.vx = self.vx - SPEED
		self.facing = -1
	end
	if love.keyboard.isDown("right", "d") then
		self.vx = self.vx + SPEED
		self.facing = 1
	end

	if (love.keyboard.isDown("space", "w") or love.keyboard.isDown("up")) and self.onGround then
		self.vy = JUMP_VELOCITY
		self.onGround = false
	end

	self.vy = self.vy + GRAVITY * dt

	self.x = self.x + self.vx * dt
	self.y = self.y + self.vy * dt

	if self.y >= groundY then
		self.y = groundY
		self.vy = 0
		self.onGround = true
	end

	-- Advance the walk cycle only while actually walking. There's no idle
	-- animation yet (see README roadmap), so just hold frame 1 when still.
	if self.vx ~= 0 and self.onGround then
		self.animTimer = self.animTimer + dt
		local frameName = walkAnim.frames[self.animFrame]
		local duration = frames[frameName].duration
		if self.animTimer >= duration then
			self.animTimer = self.animTimer - duration
			self.animFrame = self.animFrame + 1
			if self.animFrame > #walkAnim.frames then
				self.animFrame = 1
			end
		end
	else
		self.animFrame = 1
		self.animTimer = 0
	end
end

function Player:draw()
	local frameName = walkAnim.frames[self.animFrame]
	local frame = frames[frameName]

	-- Frame pivots are bottom-center (see pixegen's DEFAULT_PIVOT), matching
	-- self.x/self.y being the top-left of the collision rectangle.
	local drawX = self.x + self.width / 2
	local drawY = self.y + self.height

	love.graphics.setColor(1, 1, 1, 1)
	love.graphics.draw(spriteImage, frame.quad, drawX, drawY, 0, self.facing, 1, frame.ox, frame.oy)
end

return Player
